"""Added field into Reminder model

Revision ID: 03de31b602c0
Revises: 1922d99b388b
Create Date: 2025-05-03 12:12:39.789750

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03de31b602c0"
down_revision: Union[str, None] = "1922d99b388b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reminders",
        sa.Column("next_run_time", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix__reminders_next_run_time"),
        "reminders",
        ["next_run_time"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix__reminders_next_run_time"), table_name="reminders")
    op.drop_column("reminders", "next_run_time")
    # ### end Alembic commands ###
