"""Reminder model has been edited

Revision ID: 28d16e86d3cd
Revises: 41f2edcb6645
Create Date: 2025-04-26 13:42:17.278965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28d16e86d3cd'
down_revision: Union[str, None] = '41f2edcb6645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('custom_frequency', sa.JSON(), nullable=True))
    op.alter_column('reminders', 'apscheduler_job_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index('ix__reminders_job_id', table_name='reminders')
    op.drop_column('reminders', 'custom_interval')
    op.drop_column('reminders', 'job_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('job_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reminders', sa.Column('custom_interval', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index('ix__reminders_job_id', 'reminders', ['job_id'], unique=False)
    op.alter_column('reminders', 'apscheduler_job_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('reminders', 'custom_frequency')
    # ### end Alembic commands ###
