"""Fix models 2

Revision ID: 41f2edcb6645
Revises: 70ec814d35d4
Create Date: 2025-04-13 00:09:11.971025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41f2edcb6645'
down_revision: Union[str, None] = '70ec814d35d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('frequency_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', 'CUSTOM', name='frequency_type_enum'), nullable=False),
    sa.Column('custom_interval', sa.JSON(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('apscheduler_job_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__reminders__user_id__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__reminders'))
    )
    op.create_index(op.f('ix__reminders_apscheduler_job_id'), 'reminders', ['apscheduler_job_id'], unique=True)
    op.create_index(op.f('ix__reminders_is_active'), 'reminders', ['is_active'], unique=False)
    op.create_index(op.f('ix__reminders_job_id'), 'reminders', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__reminders_job_id'), table_name='reminders')
    op.drop_index(op.f('ix__reminders_is_active'), table_name='reminders')
    op.drop_index(op.f('ix__reminders_apscheduler_job_id'), table_name='reminders')
    op.drop_table('reminders')
    # ### end Alembic commands ###
